config/routes.rb
Mayday::Application.routes.draw do
  resources :helps

  resources :officers

  resources :police

  get "home/index"

  resources :ambulances

  root :to => 'home#index'

end

app/models/officer.rb
class Officer < ActiveRecord::Base
  attr_accessible :content, :display_addr, :name, :poi_addr, :traffic_information, :x, :y
end

app/controllers/officers_controller.rb
class OfficersController < ApplicationController
  # GET /officers
  # GET /officers.json
  def index
    @officers = Officer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @officers }
    end
  end

  # GET /officers/1
  # GET /officers/1.json
  def show
    @officer = Officer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @officer }
    end
  end

  # GET /officers/new
  # GET /officers/new.json
  def new
    @officer = Officer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @officer }
    end
  end

  # GET /officers/1/edit
  def edit
    @officer = Officer.find(params[:id])
  end

  # POST /officers
  # POST /officers.json
  def create
    @officer = Officer.new(params[:officer])

    respond_to do |format|
      if @officer.save
        format.html { redirect_to @officer, notice: 'Officer was successfully created.' }
        format.json { render json: @officer, status: :created, location: @officer }
      else
        format.html { render action: "new" }
        format.json { render json: @officer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /officers/1
  # PUT /officers/1.json
  def update
    @officer = Officer.find(params[:id])

    respond_to do |format|
      if @officer.update_attributes(params[:officer])
        format.html { redirect_to @officer, notice: 'Officer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @officer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /officers/1
  # DELETE /officers/1.json
  def destroy
    @officer = Officer.find(params[:id])
    @officer.destroy

    respond_to do |format|
      format.html { redirect_to officers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/officers_helper.rb
module OfficersHelper
end

app/views/officers/_form.html.erb
<%= form_for(@officer) do |f| %>
  <% if @officer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@officer.errors.count, "error") %> prohibited this officer from being saved:</h2>

      <ul>
      <% @officer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :traffic_information %><br />
    <%= f.text_field :traffic_information %>
  </div>
  <div class="field">
    <%= f.label :display_addr %><br />
    <%= f.text_field :display_addr %>
  </div>
  <div class="field">
    <%= f.label :poi_addr %><br />
    <%= f.text_field :poi_addr %>
  </div>
  <div class="field">
    <%= f.label :x %><br />
    <%= f.text_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br />
    <%= f.text_field :y %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/officers/edit.html.erb
<h1>Editing officer</h1>

<%= render 'form' %>

<%= link_to 'Show', @officer %> |
<%= link_to 'Back', officers_path %>

app/views/officers/index.html.erb
<h1>Listing officers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th>Traffic information</th>
    <th>Display addr</th>
    <th>Poi addr</th>
    <th>X</th>
    <th>Y</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @officers.each do |officer| %>
  <tr>
    <td><%= officer.name %></td>
    <td><%= officer.content %></td>
    <td><%= officer.traffic_information %></td>
    <td><%= officer.display_addr %></td>
    <td><%= officer.poi_addr %></td>
    <td><%= officer.x %></td>
    <td><%= officer.y %></td>
    <td><%= link_to 'Show', officer %></td>
    <td><%= link_to 'Edit', edit_officer_path(officer) %></td>
    <td><%= link_to 'Destroy', officer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Officer', new_officer_path %>

app/views/officers/new.html.erb
<h1>New officer</h1>

<%= render 'form' %>

<%= link_to 'Back', officers_path %>

app/views/officers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @officer.name %>
</p>

<p>
  <b>Content:</b>
  <%= @officer.content %>
</p>

<p>
  <b>Traffic information:</b>
  <%= @officer.traffic_information %>
</p>

<p>
  <b>Display addr:</b>
  <%= @officer.display_addr %>
</p>

<p>
  <b>Poi addr:</b>
  <%= @officer.poi_addr %>
</p>

<p>
  <b>X:</b>
  <%= @officer.x %>
</p>

<p>
  <b>Y:</b>
  <%= @officer.y %>
</p>


<%= link_to 'Edit', edit_officer_path(@officer) %> |
<%= link_to 'Back', officers_path %>