config/routes.rb
Mayday::Application.routes.draw do
  resources :helps

  resources :officers

  resources :police

  get "home/index"

  resources :ambulances

  root :to => 'home#index'

end

app/models/ambulance.rb
class Ambulance < ActiveRecord::Base
  attr_accessible :category, :display_addr, :name, :poi_addr, :tel, :traffic_info, :x, :y
end

app/controllers/ambulances_controller.rb
class AmbulancesController < ApplicationController
  # GET /ambulances
  # GET /ambulances.json
  def index
    @ambulances = Ambulance.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ambulances }
    end
  end

  # GET /ambulances/1
  # GET /ambulances/1.json
  def show
    @ambulance = Ambulance.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ambulance }
    end
  end

  # GET /ambulances/new
  # GET /ambulances/new.json
  def new
    @ambulance = Ambulance.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ambulance }
    end
  end

  # GET /ambulances/1/edit
  def edit
    @ambulance = Ambulance.find(params[:id])
  end

  # POST /ambulances
  # POST /ambulances.json
  def create
    @ambulance = Ambulance.new(params[:ambulance])

    respond_to do |format|
      if @ambulance.save
        format.html { redirect_to @ambulance, notice: 'Ambulance was successfully created.' }
        format.json { render json: @ambulance, status: :created, location: @ambulance }
      else
        format.html { render action: "new" }
        format.json { render json: @ambulance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ambulances/1
  # PUT /ambulances/1.json
  def update
    @ambulance = Ambulance.find(params[:id])

    respond_to do |format|
      if @ambulance.update_attributes(params[:ambulance])
        format.html { redirect_to @ambulance, notice: 'Ambulance was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ambulance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ambulances/1
  # DELETE /ambulances/1.json
  def destroy
    @ambulance = Ambulance.find(params[:id])
    @ambulance.destroy

    respond_to do |format|
      format.html { redirect_to ambulances_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ambulances_helper.rb
module AmbulancesHelper
end

app/views/ambulances/_form.html.erb
<%= form_for(@ambulance) do |f| %>
  <% if @ambulance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ambulance.errors.count, "error") %> prohibited this ambulance from being saved:</h2>

      <ul>
      <% @ambulance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :tel %><br />
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :traffic_info %><br />
    <%= f.text_field :traffic_info %>
  </div>
  <div class="field">
    <%= f.label :display_addr %><br />
    <%= f.text_field :display_addr %>
  </div>
  <div class="field">
    <%= f.label :poi_addr %><br />
    <%= f.text_field :poi_addr %>
  </div>
  <div class="field">
    <%= f.label :x %><br />
    <%= f.text_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br />
    <%= f.text_field :y %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ambulances/edit.html.erb
<h1>Editing ambulance</h1>

<%= render 'form' %>

<%= link_to 'Show', @ambulance %> |
<%= link_to 'Back', ambulances_path %>

app/views/ambulances/index.html.erb
<h1>Listing ambulances</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Tel</th>
    <th>Traffic info</th>
    <th>Display addr</th>
    <th>Poi addr</th>
    <th>X</th>
    <th>Y</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ambulances.each do |ambulance| %>
  <tr>
    <td><%= ambulance.name %></td>
    <td><%= ambulance.category %></td>
    <td><%= ambulance.tel %></td>
    <td><%= ambulance.traffic_info %></td>
    <td><%= ambulance.display_addr %></td>
    <td><%= ambulance.poi_addr %></td>
    <td><%= ambulance.x %></td>
    <td><%= ambulance.y %></td>
    <td><%= link_to 'Show', ambulance %></td>
    <td><%= link_to 'Edit', edit_ambulance_path(ambulance) %></td>
    <td><%= link_to 'Destroy', ambulance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ambulance', new_ambulance_path %>

app/views/ambulances/new.html.erb
<h1>New ambulance</h1>

<%= render 'form' %>

<%= link_to 'Back', ambulances_path %>

app/views/ambulances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @ambulance.name %>
</p>

<p>
  <b>Category:</b>
  <%= @ambulance.category %>
</p>

<p>
  <b>Tel:</b>
  <%= @ambulance.tel %>
</p>

<p>
  <b>Traffic info:</b>
  <%= @ambulance.traffic_info %>
</p>

<p>
  <b>Display addr:</b>
  <%= @ambulance.display_addr %>
</p>

<p>
  <b>Poi addr:</b>
  <%= @ambulance.poi_addr %>
</p>

<p>
  <b>X:</b>
  <%= @ambulance.x %>
</p>

<p>
  <b>Y:</b>
  <%= @ambulance.y %>
</p>


<%= link_to 'Edit', edit_ambulance_path(@ambulance) %> |
<%= link_to 'Back', ambulances_path %>