config/routes.rb
Mayday::Application.routes.draw do
  resources :helps

  resources :officers

  resources :police

  get "home/index"

  resources :ambulances

  root :to => 'home#index'

end

app/controllers/police_controller.rb
class PoliceController < ApplicationController
  # GET /police
  # GET /police.json
  def index
    @police = Polouse.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @police }
    end
  end

  # GET /police/1
  # GET /police/1.json
  def show
    @polouse = Polouse.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @polouse }
    end
  end

  # GET /police/new
  # GET /police/new.json
  def new
    @polouse = Polouse.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @polouse }
    end
  end

  # GET /police/1/edit
  def edit
    @polouse = Polouse.find(params[:id])
  end

  # POST /police
  # POST /police.json
  def create
    @polouse = Polouse.new(params[:polouse])

    respond_to do |format|
      if @polouse.save
        format.html { redirect_to @polouse, notice: 'Polouse was successfully created.' }
        format.json { render json: @polouse, status: :created, location: @polouse }
      else
        format.html { render action: "new" }
        format.json { render json: @polouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /police/1
  # PUT /police/1.json
  def update
    @polouse = Polouse.find(params[:id])

    respond_to do |format|
      if @polouse.update_attributes(params[:polouse])
        format.html { redirect_to @polouse, notice: 'Polouse was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @polouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /police/1
  # DELETE /police/1.json
  def destroy
    @polouse = Polouse.find(params[:id])
    @polouse.destroy

    respond_to do |format|
      format.html { redirect_to police_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/police_helper.rb
module PoliceHelper
end

app/views/police/_form.html.erb
<%= form_for(@polouse) do |f| %>
  <% if @polouse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@polouse.errors.count, "error") %> prohibited this polouse from being saved:</h2>

      <ul>
      <% @polouse.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :traffic_information %><br />
    <%= f.text_field :traffic_information %>
  </div>
  <div class="field">
    <%= f.label :display_addr %><br />
    <%= f.text_field :display_addr %>
  </div>
  <div class="field">
    <%= f.label :poi_addr %><br />
    <%= f.text_field :poi_addr %>
  </div>
  <div class="field">
    <%= f.label :x %><br />
    <%= f.text_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br />
    <%= f.text_field :y %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/police/edit.html.erb
<h1>Editing polouse</h1>

<%= render 'form' %>

<%= link_to 'Show', @polouse %> |
<%= link_to 'Back', police_path %>

app/views/police/index.html.erb
<h1>Listing police</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th>Traffic information</th>
    <th>Display addr</th>
    <th>Poi addr</th>
    <th>X</th>
    <th>Y</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @police.each do |polouse| %>
  <tr>
    <td><%= polouse.name %></td>
    <td><%= polouse.content %></td>
    <td><%= polouse.traffic_information %></td>
    <td><%= polouse.display_addr %></td>
    <td><%= polouse.poi_addr %></td>
    <td><%= polouse.x %></td>
    <td><%= polouse.y %></td>
    <td><%= link_to 'Show', polouse %></td>
    <td><%= link_to 'Edit', edit_polouse_path(polouse) %></td>
    <td><%= link_to 'Destroy', polouse, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Polouse', new_polouse_path %>

app/views/police/new.html.erb
<h1>New polouse</h1>

<%= render 'form' %>

<%= link_to 'Back', police_path %>

app/views/police/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @polouse.name %>
</p>

<p>
  <b>Content:</b>
  <%= @polouse.content %>
</p>

<p>
  <b>Traffic information:</b>
  <%= @polouse.traffic_information %>
</p>

<p>
  <b>Display addr:</b>
  <%= @polouse.display_addr %>
</p>

<p>
  <b>Poi addr:</b>
  <%= @polouse.poi_addr %>
</p>

<p>
  <b>X:</b>
  <%= @polouse.x %>
</p>

<p>
  <b>Y:</b>
  <%= @polouse.y %>
</p>


<%= link_to 'Edit', edit_polouse_path(@polouse) %> |
<%= link_to 'Back', police_path %>