config/routes.rb
Mayday::Application.routes.draw do
  resources :helps

  resources :officers

  resources :police

  get "home/index"

  resources :ambulances

  root :to => 'home#index'

end

app/models/help.rb
class Help < ActiveRecord::Base
  attr_accessible :description, :name, :x, :y
end

app/controllers/helps_controller.rb
class HelpsController < ApplicationController
  # GET /helps
  # GET /helps.json
  def index
    @helps = Help.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @helps }
    end
  end

  # GET /helps/1
  # GET /helps/1.json
  def show
    @help = Help.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @help }
    end
  end

  # GET /helps/new
  # GET /helps/new.json
  def new
    @help = Help.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @help }
    end
  end

  # GET /helps/1/edit
  def edit
    @help = Help.find(params[:id])
  end

  # POST /helps
  # POST /helps.json
  def create
    @help = Help.new(params[:help])

    respond_to do |format|
      if @help.save
        format.html { redirect_to @help, notice: 'Help was successfully created.' }
        format.json { render json: @help, status: :created, location: @help }
      else
        format.html { render action: "new" }
        format.json { render json: @help.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /helps/1
  # PUT /helps/1.json
  def update
    @help = Help.find(params[:id])

    respond_to do |format|
      if @help.update_attributes(params[:help])
        format.html { redirect_to @help, notice: 'Help was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @help.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /helps/1
  # DELETE /helps/1.json
  def destroy
    @help = Help.find(params[:id])
    @help.destroy

    respond_to do |format|
      format.html { redirect_to helps_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/views/helps/_form.html.erb
<%= form_for(@help) do |f| %>
  <% if @help.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@help.errors.count, "error") %> prohibited this help from being saved:</h2>

      <ul>
      <% @help.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :x %><br />
    <%= f.text_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br />
    <%= f.text_field :y %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/helps/edit.html.erb
<h1>Editing help</h1>

<%= render 'form' %>

<%= link_to 'Show', @help %> |
<%= link_to 'Back', helps_path %>

app/views/helps/index.html.erb
<h1>Listing helps</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>X</th>
    <th>Y</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @helps.each do |help| %>
  <tr>
    <td><%= help.name %></td>
    <td><%= help.description %></td>
    <td><%= help.x %></td>
    <td><%= help.y %></td>
    <td><%= link_to 'Show', help %></td>
    <td><%= link_to 'Edit', edit_help_path(help) %></td>
    <td><%= link_to 'Destroy', help, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Help', new_help_path %>

app/views/helps/new.html.erb
<h1>New help</h1>

<%= render 'form' %>

<%= link_to 'Back', helps_path %>

app/views/helps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @help.name %>
</p>

<p>
  <b>Description:</b>
  <%= @help.description %>
</p>

<p>
  <b>X:</b>
  <%= @help.x %>
</p>

<p>
  <b>Y:</b>
  <%= @help.y %>
</p>


<%= link_to 'Edit', edit_help_path(@help) %> |
<%= link_to 'Back', helps_path %>